import { Case, KnowledgeArticle, SearchResult, Event, TaskTile } from './types';

export const mockEvents: Event[] = [
  {
    id: 'EVT-123456',
    name: 'Taylor Swift - Eras Tour',
    date: new Date('2024-02-15T19:00:00'),
    venue: 'Madison Square Garden',
    status: 'upcoming',
  },
  {
    id: 'EVT-234567',
    name: 'Beyoncé - Renaissance World Tour',
    date: new Date('2024-02-20T20:00:00'),
    venue: 'Madison Square Garden',
    status: 'upcoming',
  },
  {
    id: 'EVT-345678',
    name: 'NBA All-Star Game 2024',
    date: new Date('2024-02-18T18:00:00'),
    venue: 'Madison Square Garden',
    status: 'upcoming',
  },
  {
    id: 'EVT-456789',
    name: 'New York Rangers vs Boston Bruins',
    date: new Date('2024-01-25T19:30:00'),
    venue: 'Madison Square Garden',
    status: 'past',
  },
  {
    id: 'EVT-567890',
    name: 'Billy Joel Monthly Residency',
    date: new Date('2024-01-20T20:00:00'),
    venue: 'Madison Square Garden',
    status: 'past',
  },
  {
    id: 'EVT-678901',
    name: 'WWE Monday Night Raw',
    date: new Date('2024-02-26T19:00:00'),
    venue: 'Madison Square Garden',
    status: 'upcoming',
  },
];

export const taskTiles: TaskTile[] = [
  {
    id: 'prepare-onsale',
    title: 'Prepare for Onsale',
    description: 'Set up presales, pricing tiers, and inventory',
    icon: 'ticket',
    href: '/knowledge?category=onsale',
    color: 'primary',
  },
  {
    id: 'event-day-setup',
    title: 'Event-Day Setup',
    description: 'Scanners, access control, and gate operations',
    icon: 'calendar',
    href: '/knowledge?category=event-day',
    color: 'secondary',
  },
  {
    id: 'settlement-reports',
    title: 'Settlement & Reports',
    description: 'Financial reconciliation and reporting',
    icon: 'dollar',
    href: '/knowledge?category=settlement',
    color: 'accent',
  },
  {
    id: 'access-control',
    title: 'Access Control & Scanning',
    description: 'Device setup and troubleshooting',
    icon: 'scan',
    href: '/knowledge?category=scanning',
    color: 'warning',
  },
];

export const quickLinks = [
  {
    id: 'tm1',
    title: 'TM1',
    description: 'Event management platform',
    href: 'https://tm1.ticketmaster.com',
    icon: 'ticket',
  },
  {
    id: 'virtual-venue',
    title: 'Virtual Venue',
    description: '3D venue visualization',
    href: 'https://virtualvenue.ticketmaster.com',
    icon: 'map',
  },
  {
    id: 'safetix',
    title: 'SafeTix',
    description: 'Secure digital ticketing',
    href: 'https://safetix.ticketmaster.com',
    icon: 'shield',
  },
  {
    id: 'account-manager',
    title: 'Account Manager',
    description: 'Client account portal',
    href: 'https://accountmanager.ticketmaster.com',
    icon: 'user',
  },
  {
    id: 'support-community',
    title: 'Support Community',
    description: 'Forums and peer support',
    href: 'https://community.ticketmaster.com',
    icon: 'users',
  },
];

export const mockCases: Case[] = [
  {
    id: '1',
    caseNumber: 'TM-2024-00001',
    category: 'event-day',
    subCategory: 'scanner-sync',
    eventId: 'EVT-123456',
    eventName: 'Taylor Swift - Eras Tour',
    venuePartnerId: 'VEN-001',
    market: 'us',
    urgency: 'critical',
    description: 'Scanners at Gate A are not syncing with the main system. Event starts in 4 hours.',
    triedSolutions: ['device-diagnostics', 'sample-scan'],
    attachments: [],
    status: 'in-progress',
    assignedQueue: 'Event-Day Ops',
    createdAt: new Date('2024-01-15T10:30:00'),
    updatedAt: new Date('2024-01-15T11:45:00'),
    slaDeadline: new Date('2024-01-15T11:30:00'),
    comments: [
      {
        id: 'c1',
        author: 'Support Agent',
        content: 'Escalating to Event-Day Ops team. A technician will contact you shortly.',
        createdAt: new Date('2024-01-15T10:45:00'),
        isInternal: false,
      },
    ],
    contactName: 'John Smith',
    contactEmail: 'john.smith@venue.com',
    partnerId: 'PTR-001',
    role: 'Venue Operations Manager',
    company: 'Madison Square Garden',
    source: 'portal',
  },
  {
    id: '2',
    caseNumber: 'TM-2024-00002',
    category: 'settlement-payments',
    subCategory: 'settlement-discrepancy',
    venuePartnerId: 'VEN-002',
    market: 'uk',
    urgency: 'normal',
    description: 'Settlement report shows $5,000 discrepancy from expected revenue for last week\'s concert series.',
    triedSolutions: ['visited-help-center'],
    attachments: [],
    status: 'open',
    assignedQueue: 'Settlement Team',
    createdAt: new Date('2024-01-14T09:00:00'),
    updatedAt: new Date('2024-01-14T09:00:00'),
    slaDeadline: new Date('2024-01-16T09:00:00'),
    comments: [],
    contactName: 'Sarah Johnson',
    contactEmail: 'sarah.j@promoter.co.uk',
    partnerId: 'PTR-002',
    role: 'Finance Director',
    company: 'LiveNation UK',
    source: 'email',
  },
  {
    id: '3',
    caseNumber: 'TM-2024-00003',
    category: 'technical-integration',
    subCategory: 'api-error',
    eventId: 'EVT-789012',
    eventName: 'Summer Music Festival',
    venuePartnerId: 'VEN-003',
    market: 'de',
    urgency: 'high',
    description: 'API returning 429 rate limit errors despite staying within documented limits. Affecting ticket sales integration.',
    triedSolutions: ['visited-help-center', 'reviewed-checklist'],
    attachments: [],
    status: 'pending',
    assignedQueue: 'Technical Support',
    createdAt: new Date('2024-01-13T14:20:00'),
    updatedAt: new Date('2024-01-14T08:30:00'),
    slaDeadline: new Date('2024-01-14T18:20:00'),
    comments: [
      {
        id: 'c2',
        author: 'Technical Support',
        content: 'We\'ve identified increased traffic from your IP range. Can you confirm the number of concurrent requests?',
        createdAt: new Date('2024-01-13T15:00:00'),
        isInternal: false,
      },
      {
        id: 'c3',
        author: 'Partner',
        content: 'We\'re making approximately 100 requests per minute, which is within the 150/min limit.',
        createdAt: new Date('2024-01-13T16:30:00'),
        isInternal: false,
      },
    ],
    contactName: 'Hans Mueller',
    contactEmail: 'h.mueller@ticketing-platform.de',
    partnerId: 'PTR-003',
    role: 'Lead Developer',
    company: 'EventTech GmbH',
    source: 'portal',
  },
  {
    id: '4',
    caseNumber: 'TM-2024-00004',
    category: 'ticketing-presale',
    subCategory: 'presale-setup',
    eventId: 'EVT-456789',
    eventName: 'Taylor Swift - Eras Tour',
    venuePartnerId: 'VEN-001',
    market: 'us',
    urgency: 'normal',
    description: 'Need assistance setting up tiered presale for Taylor Swift concert. VIP, Platinum, and General presale codes.',
    triedSolutions: ['visited-help-center'],
    attachments: [],
    status: 'resolved',
    assignedQueue: 'Ticketing Support',
    createdAt: new Date('2024-01-10T11:00:00'),
    updatedAt: new Date('2024-01-12T15:00:00'),
    slaDeadline: new Date('2024-01-12T11:00:00'),
    comments: [
      {
        id: 'c4',
        author: 'Ticketing Support',
        content: 'Presale configuration complete. All tiers are active and ready for the scheduled dates.',
        createdAt: new Date('2024-01-12T15:00:00'),
        isInternal: false,
      },
    ],
    contactName: 'John Smith',
    contactEmail: 'john.smith@venue.com',
    partnerId: 'PTR-001',
    role: 'Venue Operations Manager',
    company: 'Madison Square Garden',
    source: 'phone',
  },
  {
    id: '5',
    caseNumber: 'TM-2024-00005',
    category: 'inventory-pricing',
    subCategory: 'dynamic-pricing',
    venuePartnerId: 'VEN-004',
    market: 'ca',
    urgency: 'low',
    description: 'Question about implementing dynamic pricing for upcoming hockey season. Looking for best practices and setup guidance.',
    triedSolutions: ['visited-help-center'],
    attachments: [],
    status: 'closed',
    assignedQueue: 'Pricing Team',
    createdAt: new Date('2024-01-08T16:00:00'),
    updatedAt: new Date('2024-01-09T10:00:00'),
    slaDeadline: new Date('2024-01-15T16:00:00'),
    comments: [
      {
        id: 'c5',
        author: 'Pricing Team',
        content: 'Please review the Dynamic Pricing Guide linked in your portal. We\'ll schedule a call to discuss implementation details.',
        createdAt: new Date('2024-01-09T10:00:00'),
        isInternal: false,
      },
    ],
    contactName: 'Marie Leblanc',
    contactEmail: 'marie@hockeyarena.ca',
    partnerId: 'PTR-004',
    role: 'Revenue Manager',
    company: 'Toronto Sports Arena',
    source: 'portal',
  },
];

export const mockKnowledgeArticles: KnowledgeArticle[] = [
  {
    id: 'kb1',
    title: 'Scanner Troubleshooting Guide',
    description: 'Step-by-step guide to diagnose and resolve common scanner issues on event day.',
    type: 'article',
    url: '/knowledge/scanner-troubleshooting',
    source: 'TM1 Documentation',
    relevanceScore: 0.95,
  },
  {
    id: 'kb2',
    title: 'Event-Day Operations Checklist',
    description: 'Comprehensive checklist for venue staff to ensure smooth event-day operations.',
    type: 'article',
    url: '/knowledge/event-day-checklist',
    source: 'Internal Docs',
    relevanceScore: 0.88,
  },
  {
    id: 'kb3',
    title: 'Scanner Sync: Video Tutorial',
    description: 'Watch how to properly sync scanners with the central system before an event.',
    type: 'video',
    url: '/training/scanner-sync-video',
    source: 'Training Library',
    relevanceScore: 0.92,
  },
  {
    id: 'kb4',
    title: 'API Rate Limits and Best Practices',
    description: 'Understanding API rate limits and how to optimize your integration.',
    type: 'article',
    url: '/knowledge/api-rate-limits',
    source: 'Developer Portal',
    relevanceScore: 0.85,
  },
  {
    id: 'kb5',
    title: 'Settlement Reports Explained',
    description: 'How to read and reconcile settlement reports with your internal systems.',
    type: 'training',
    url: '/training/settlement-reports',
    source: 'Partner Academy',
    relevanceScore: 0.80,
  },
  {
    id: 'kb6',
    title: 'Presale Setup Guide',
    description: 'Complete guide to setting up presales, access codes, and fan verification.',
    type: 'article',
    url: '/knowledge/presale-setup',
    source: 'TM1 Documentation',
    relevanceScore: 0.90,
  },
];

export const mockSearchResults: SearchResult[] = [
  {
    id: 'sr1',
    title: 'Scanner Troubleshooting Guide',
    snippet: 'Common issues include Wi-Fi connectivity, battery status, and software version mismatches...',
    type: 'knowledge',
    source: 'TM1 Documentation',
    url: '/knowledge/scanner-troubleshooting',
    date: new Date('2024-01-10'),
  },
  {
    id: 'sr2',
    title: 'Event-Day Operations Checklist',
    snippet: 'Ensure all scanners are charged to at least 80% before gates open...',
    type: 'knowledge',
    source: 'Internal Docs',
    url: '/knowledge/event-day-checklist',
    date: new Date('2024-01-08'),
  },
  {
    id: 'sr3',
    title: 'Scanner Sync Training Video',
    snippet: 'Step-by-step video guide for syncing venue scanners with the central management system...',
    type: 'video',
    source: 'Training Library',
    url: '/training/scanner-sync-video',
    date: new Date('2023-12-15'),
  },
  {
    id: 'sr4',
    title: 'API Integration Best Practices',
    snippet: 'Learn how to optimize API calls and handle rate limiting effectively...',
    type: 'knowledge',
    source: 'Developer Portal',
    url: '/knowledge/api-best-practices',
    date: new Date('2024-01-05'),
  },
  {
    id: 'sr5',
    title: 'Understanding Settlement Reports',
    snippet: 'A comprehensive guide to reading and reconciling your settlement statements...',
    type: 'training',
    source: 'Partner Academy',
    url: '/training/settlement-reports',
    date: new Date('2023-11-20'),
  },
];

export const currentUser = {
  name: 'John Smith',
  email: 'john.smith@venue.com',
  partnerId: 'PTR-001',
  role: 'Venue Operations Manager',
  company: 'Madison Square Garden',
  market: 'us',
};
