import { Case, KnowledgeArticle, SearchResult, Event, TaskTile } from './types';

// Account context - Ed Sheeran Mathematics Tour
export const currentAccount = {
  id: 'ACC-EDSHEERAN-2024',
  name: 'Ed Sheeran - Mathematics Tour',
  artist: 'Ed Sheeran',
  tourName: 'Mathematics Tour',
  promoter: 'Touring Productions Ltd',
  region: 'North America',
};

export const mockEvents: Event[] = [
  {
    id: 'EVT-ES-001',
    name: 'Ed Sheeran - Mathematics Tour (Night 1)',
    date: new Date('2024-03-15T19:30:00'),
    venue: 'MetLife Stadium',
    status: 'upcoming',
  },
  {
    id: 'EVT-ES-002',
    name: 'Ed Sheeran - Mathematics Tour (Night 2)',
    date: new Date('2024-03-16T19:30:00'),
    venue: 'MetLife Stadium',
    status: 'upcoming',
  },
  {
    id: 'EVT-ES-003',
    name: 'Ed Sheeran - Mathematics Tour',
    date: new Date('2024-03-22T20:00:00'),
    venue: 'Gillette Stadium',
    status: 'upcoming',
  },
  {
    id: 'EVT-ES-004',
    name: 'Ed Sheeran - Mathematics Tour',
    date: new Date('2024-03-29T19:00:00'),
    venue: 'Lincoln Financial Field',
    status: 'upcoming',
  },
  {
    id: 'EVT-ES-005',
    name: 'Ed Sheeran - Mathematics Tour',
    date: new Date('2024-02-10T19:30:00'),
    venue: 'AT&T Stadium',
    status: 'past',
  },
  {
    id: 'EVT-ES-006',
    name: 'Ed Sheeran - Mathematics Tour',
    date: new Date('2024-02-03T20:00:00'),
    venue: 'SoFi Stadium',
    status: 'past',
  },
];

export const taskTiles: TaskTile[] = [
  {
    id: 'prepare-onsale',
    title: 'Prepare for Onsale',
    description: 'Set up presales, pricing tiers, and inventory',
    icon: 'ticket',
    href: '/knowledge?category=onsale',
    color: 'primary',
  },
  {
    id: 'event-day-setup',
    title: 'Event-Day Setup',
    description: 'Scanners, access control, and gate operations',
    icon: 'calendar',
    href: '/knowledge?category=event-day',
    color: 'secondary',
  },
  {
    id: 'settlement-reports',
    title: 'Settlement & Reports',
    description: 'Financial reconciliation and reporting',
    icon: 'dollar',
    href: '/knowledge?category=settlement',
    color: 'accent',
  },
  {
    id: 'access-control',
    title: 'Access Control & Scanning',
    description: 'Device setup and troubleshooting',
    icon: 'scan',
    href: '/knowledge?category=scanning',
    color: 'warning',
  },
];

export const quickLinks = [
  {
    id: 'tm1',
    title: 'TM1',
    description: 'Event management platform',
    href: 'https://tm1.ticketmaster.com',
    icon: 'ticket',
  },
  {
    id: 'account-manager',
    title: 'Account Manager',
    description: 'Client account portal',
    href: 'https://accountmanager.ticketmaster.com',
    icon: 'user',
  },
  {
    id: 'safetix',
    title: 'SafeTix',
    description: 'Secure digital ticketing',
    href: 'https://safetix.ticketmaster.com',
    icon: 'shield',
  },
  {
    id: 'virtual-venue',
    title: 'Virtual Venue',
    description: '3D venue visualization',
    href: 'https://virtualvenue.ticketmaster.com',
    icon: 'map',
  },
];

export const mockCases: Case[] = [
  {
    id: '1',
    caseNumber: 'TM-2024-00001',
    category: 'event-day',
    subCategory: 'scanner-sync',
    eventId: 'EVT-ES-001',
    eventName: 'Ed Sheeran - Mathematics Tour (Night 1)',
    venuePartnerId: 'VEN-METLIFE',
    market: 'us',
    urgency: 'critical',
    description: 'Scanners at Gate A are not syncing with the main system. Event starts in 4 hours.',
    triedSolutions: ['device-diagnostics', 'sample-scan'],
    attachments: [],
    status: 'in-progress',
    assignedQueue: 'Event-Day Ops',
    createdAt: new Date(),
    updatedAt: new Date(),
    slaDeadline: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours overdue
    comments: [
      {
        id: 'c1',
        author: 'Support Agent',
        content: 'Escalating to Event-Day Ops team. A technician will contact you shortly.',
        createdAt: new Date('2024-03-15T10:45:00'),
        isInternal: false,
      },
    ],
    contactName: 'Rachel Green',
    contactEmail: 'rachel.green@touringprod.com',
    partnerId: 'PTR-EDSHEERAN',
    role: 'Tour Production Manager',
    company: 'Touring Productions Ltd',
    source: 'portal',
  },
  {
    id: '2',
    caseNumber: 'TM-2024-00002',
    category: 'settlement-payments',
    subCategory: 'settlement-discrepancy',
    eventId: 'EVT-ES-005',
    eventName: 'Ed Sheeran - Mathematics Tour (AT&T Stadium)',
    venuePartnerId: 'VEN-ATT',
    market: 'us',
    urgency: 'normal',
    description: 'Settlement report shows $12,500 discrepancy from expected revenue for the AT&T Stadium show on Feb 10.',
    triedSolutions: ['visited-help-center'],
    attachments: [],
    status: 'open',
    assignedQueue: 'Settlement Team',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    slaDeadline: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours remaining
    comments: [],
    contactName: 'Marcus Chen',
    contactEmail: 'marcus.chen@touringprod.com',
    partnerId: 'PTR-EDSHEERAN',
    role: 'Finance Manager',
    company: 'Touring Productions Ltd',
    source: 'email',
  },
  {
    id: '3',
    caseNumber: 'TM-2024-00003',
    category: 'technical-integration',
    subCategory: 'api-error',
    eventId: 'EVT-ES-003',
    eventName: 'Ed Sheeran - Mathematics Tour (Gillette Stadium)',
    venuePartnerId: 'VEN-GILLETTE',
    market: 'us',
    urgency: 'high',
    description: 'API returning 429 rate limit errors when pulling real-time ticket inventory for the Gillette show. Need resolution before fan club presale.',
    triedSolutions: ['visited-help-center', 'reviewed-checklist'],
    attachments: [],
    status: 'pending',
    assignedQueue: 'Technical Support',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    slaDeadline: new Date(Date.now() + 4 * 60 * 60 * 1000), // 4 hours remaining
    comments: [
      {
        id: 'c2',
        author: 'Technical Support',
        content: 'We\'ve identified increased traffic from your IP range. Can you confirm the number of concurrent requests?',
        createdAt: new Date('2024-03-13T15:00:00'),
        isInternal: false,
      },
      {
        id: 'c3',
        author: 'Partner',
        content: 'We\'re making approximately 100 requests per minute, which is within the 150/min limit.',
        createdAt: new Date('2024-03-13T16:30:00'),
        isInternal: false,
      },
    ],
    contactName: 'James Wilson',
    contactEmail: 'james.wilson@touringprod.com',
    partnerId: 'PTR-EDSHEERAN',
    role: 'Technical Director',
    company: 'Touring Productions Ltd',
    source: 'portal',
  },
  {
    id: '4',
    caseNumber: 'TM-2024-00004',
    category: 'ticketing-presale',
    subCategory: 'presale-setup',
    eventId: 'EVT-ES-002',
    eventName: 'Ed Sheeran - Mathematics Tour (Night 2)',
    venuePartnerId: 'VEN-METLIFE',
    market: 'us',
    urgency: 'normal',
    description: 'Need assistance setting up Sheeran Fan Club presale codes for Night 2. VIP packages and Verified Fan access.',
    triedSolutions: ['visited-help-center'],
    attachments: [],
    status: 'resolved',
    assignedQueue: 'Ticketing Support',
    createdAt: new Date('2024-03-01T11:00:00'),
    updatedAt: new Date('2024-03-03T15:00:00'),
    slaDeadline: new Date('2024-03-03T11:00:00'),
    comments: [
      {
        id: 'c4',
        author: 'Ticketing Support',
        content: 'Fan Club presale and Verified Fan configuration complete. All tiers are active for the scheduled dates.',
        createdAt: new Date('2024-03-03T15:00:00'),
        isInternal: false,
      },
    ],
    contactName: 'Rachel Green',
    contactEmail: 'rachel.green@touringprod.com',
    partnerId: 'PTR-EDSHEERAN',
    role: 'Tour Production Manager',
    company: 'Touring Productions Ltd',
    source: 'phone',
  },
  {
    id: '5',
    caseNumber: 'TM-2024-00005',
    category: 'inventory-pricing',
    subCategory: 'dynamic-pricing',
    eventId: 'EVT-ES-004',
    eventName: 'Ed Sheeran - Mathematics Tour (Lincoln Financial Field)',
    venuePartnerId: 'VEN-LINCOLN',
    market: 'us',
    urgency: 'low',
    description: 'Question about implementing Platinum pricing for the Philadelphia show. Looking for optimal price floor/ceiling recommendations.',
    triedSolutions: ['visited-help-center'],
    attachments: [],
    status: 'closed',
    assignedQueue: 'Pricing Team',
    createdAt: new Date('2024-02-20T16:00:00'),
    updatedAt: new Date('2024-02-21T10:00:00'),
    slaDeadline: new Date('2024-02-27T16:00:00'),
    comments: [
      {
        id: 'c5',
        author: 'Pricing Team',
        content: 'Based on similar stadium shows, we recommend a floor of $150 and ceiling of $450 for Platinum seats. Full analysis attached.',
        createdAt: new Date('2024-02-21T10:00:00'),
        isInternal: false,
      },
    ],
    contactName: 'Marcus Chen',
    contactEmail: 'marcus.chen@touringprod.com',
    partnerId: 'PTR-EDSHEERAN',
    role: 'Finance Manager',
    company: 'Touring Productions Ltd',
    source: 'portal',
  },
];

export const mockKnowledgeArticles: KnowledgeArticle[] = [
  {
    id: 'kb1',
    title: 'Scanner Troubleshooting Guide',
    description: 'Step-by-step guide to diagnose and resolve common scanner issues on event day.',
    type: 'article',
    url: '/knowledge/scanner-troubleshooting',
    source: 'TM1 Documentation',
    relevanceScore: 0.95,
  },
  {
    id: 'kb2',
    title: 'Event-Day Operations Checklist',
    description: 'Comprehensive checklist for venue staff to ensure smooth event-day operations.',
    type: 'article',
    url: '/knowledge/event-day-checklist',
    source: 'Internal Docs',
    relevanceScore: 0.88,
  },
  {
    id: 'kb3',
    title: 'Scanner Sync: Video Tutorial',
    description: 'Watch how to properly sync scanners with the central system before an event.',
    type: 'video',
    url: '/training/scanner-sync-video',
    source: 'Training Library',
    relevanceScore: 0.92,
  },
  {
    id: 'kb4',
    title: 'API Rate Limits and Best Practices',
    description: 'Understanding API rate limits and how to optimize your integration.',
    type: 'article',
    url: '/knowledge/api-rate-limits',
    source: 'Developer Portal',
    relevanceScore: 0.85,
  },
  {
    id: 'kb5',
    title: 'Settlement Reports Explained',
    description: 'How to read and reconcile settlement reports with your internal systems.',
    type: 'training',
    url: '/training/settlement-reports',
    source: 'Partner Academy',
    relevanceScore: 0.80,
  },
  {
    id: 'kb6',
    title: 'Presale Setup Guide',
    description: 'Complete guide to setting up presales, access codes, and fan verification.',
    type: 'article',
    url: '/knowledge/presale-setup',
    source: 'TM1 Documentation',
    relevanceScore: 0.90,
  },
];

export const mockSearchResults: SearchResult[] = [
  {
    id: 'sr1',
    title: 'Scanner Troubleshooting Guide',
    snippet: 'Common issues include Wi-Fi connectivity, battery status, and software version mismatches...',
    type: 'knowledge',
    source: 'TM1 Documentation',
    url: '/knowledge/scanner-troubleshooting',
    date: new Date('2024-01-10'),
  },
  {
    id: 'sr2',
    title: 'Event-Day Operations Checklist',
    snippet: 'Ensure all scanners are charged to at least 80% before gates open...',
    type: 'knowledge',
    source: 'Internal Docs',
    url: '/knowledge/event-day-checklist',
    date: new Date('2024-01-08'),
  },
  {
    id: 'sr3',
    title: 'Scanner Sync Training Video',
    snippet: 'Step-by-step video guide for syncing venue scanners with the central management system...',
    type: 'video',
    source: 'Training Library',
    url: '/training/scanner-sync-video',
    date: new Date('2023-12-15'),
  },
  {
    id: 'sr4',
    title: 'API Integration Best Practices',
    snippet: 'Learn how to optimize API calls and handle rate limiting effectively...',
    type: 'knowledge',
    source: 'Developer Portal',
    url: '/knowledge/api-best-practices',
    date: new Date('2024-01-05'),
  },
  {
    id: 'sr5',
    title: 'Understanding Settlement Reports',
    snippet: 'A comprehensive guide to reading and reconciling your settlement statements...',
    type: 'training',
    source: 'Partner Academy',
    url: '/training/settlement-reports',
    date: new Date('2023-11-20'),
  },
];

export const currentUser = {
  name: 'Rachel Green',
  email: 'rachel.green@touringprod.com',
  partnerId: 'PTR-EDSHEERAN',
  role: 'Tour Production Manager',
  company: 'Touring Productions Ltd',
  market: 'us',
  accountId: 'ACC-EDSHEERAN-2024',
  accountName: 'Ed Sheeran - Mathematics Tour',
};
